#pragma once

#define TEXTURES_LAST TEXTURE_CUBEMAP_SKYBOX
enum TextureType
{
	TEXTURE_NONE = -1,
	TEXTURE_ATLAS_CHUNK = 0,
	TEXTURE_UI_CROSSHAIR,
	TEXTURE_UI_TOOLBAR,
	TEXTURE_UI_TOOLBAR_HIGHLIGHT,
	TEXTURE_CUBEMAP_SKYBOX
};

#define SHADERS_LAST SHADER_CUBEMAP
enum ShaderType {
	SHADER_CHUNK = 0,
	SHADER_OUTLINE,
	SHADER_BASIC_TEXTURE,
	SHADER_BASIC_COLOR,
	SHADER_CUBEMAP
};